Feature/otc 1005: display zero in summaries
openimis/openimis-fe-contribution_js pull request #13
Opened 2023-04-20 12:05 UTC by lruzicki

Ticket:
https://openimis.atlassian.net/browse/OTC-1005

Changes:
- zero instead of NaN is displayed when contribution paid or balance is equal to zero

2023-04-20 12:24 UTC, olewandowski1 commented on src/actions.js
> +
Actually, I'm not sure what's this _fetchPoliciesPremiums2_ function doing. Isn't it just declared and not used?

2023-04-20 12:32 UTC, olewandowski1 commented on src/components/ContributionForm.js
> +            fetchPoliciesPremiums(modulesManager, [`policyUuids: "${policy_uuid}"`]);
In my opinion, it would be better if you remove this _[`policyUuids: "${policy_uuid}"`]_ from here and you'll just pass _policy_uuid_ as a argument. Then, inside the _fetchPoliciesPremiums_ function in _action.js_ you will create a _filters_ variable. This is in a shortcut what I mean: 
`
fetchPoliciesPremiums(modulesManager, policy_uuid);

export function fetchPoliciesPremiums(mm, policyUuid) {
  const filters = [];
  if (policyUuid) filters.push(`policyUuids: "${policyUuid}"`);
  let payload = formatPageQueryWithCount("premiumsByPolicies", filters, [
    "id",
    "uuid",
    "payDate",
    `payer${mm.getProjection("payer.PayerPicker.projection")}`,
    "amount",
    "payType",
    "receipt",
    "isPhotoFee",
  ]);
  return graphql(payload, "CONTRIBUTION_POLICES_PREMIUMS");
}
`

2023-04-20 12:35 UTC, olewandowski1 requested changes
@lruzicki I left some comments. Refer to them if possible.

2023-04-20 13:52 UTC, olewandowski1 approved these changes
LGTM

2023-04-25 08:10 UTC, delcroip approved these changes

2023-04-25 08:10 UTC, merged